settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: web-service
  path: .
  env:
    DATABASE_CONNECTION: "mongodb://127.0.0.1:27017/?gssapiServiceName=mongodb"
    DATABASE_NAME: "sas"
  commands:
    install:
      status: true
      method: go build -o ./bin/api
    run:
      status: true
      method: ./bin/api
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
